### ISSUE TITLE
Flashing/loading bitsreams via kasli-i2c

### ISSUE THREAD

**Issue by RHanley1** [quartiq/phaser#12]
Loading bitstreams to phaser is difficult using JTAG when combined in a rack system. I see that kasli-i2c has a flash_phaser script. Are there flashing/loading instructions for this?

**Comment by jordens** [comment]
I haven't tested it in a long time. You have to experiment. It might still work but there is Kasli-v1/v2 divergence etc.
This is also not the right repository.
